# Generated by Django 5.2.6 on 2025-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theater", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("performance", "row", "seat"),
                name="unique_seat_per_performance",
            ),
        ),
    ]
